name: Sync Release to SoftwareCenter

on:
  release:
    types: [published]

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up variables
        id: vars
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT

      - name: Download release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p release_assets
          gh release download "$GITHUB_REF_NAME" \
            --repo "$GITHUB_REPOSITORY" --dir release_assets

      - name: Clone SoftwareCenter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/PlaxtonFlarion/SoftwareCenter.git software-center

      - name: Clean target directory
        run: |
          rm -rf software-center/${{ steps.vars.outputs.REPO_NAME }}
          mkdir -p software-center/${{ steps.vars.outputs.REPO_NAME }}

      - name: Copy files
        run: |
          cp README.md software-center/${{ steps.vars.outputs.REPO_NAME }}/ || true
          cp LICENSE.md software-center/${{ steps.vars.outputs.REPO_NAME }}/ || true
          cp release_assets/* software-center/${{ steps.vars.outputs.REPO_NAME }}/ || true

      - name: Push to SoftwareCenter
        run: |
          cd software-center
          git add .
          git commit -m "Sync ${{ steps.vars.outputs.REPO_NAME }} release $GITHUB_REF_NAME"
          git push
